#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

/* Inclusions specific to TCP socket programming. */
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* This needs to be generated by the user. */
#include "client_server_const.h"

/* TODO:
   Add some sort of encryption (if deemed necessary).
 */

int main(void) {



   return 0; /* TODO: Add other status return codes. */
}

