#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

/* Inclusions specific to TCP socket programming. */
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* This needs to be generated by the user. */
#include "client_server_const.h"

/* Provides a shorthand way of handling errors. */
void error(const char *msg) {
	perror(msg);
	exit(-1); /* TODO: Add other status return codes. */
}

/* TODO: Add docstring. */
int main(void) {
   int sock_fd = -1; /* Socket file descriptor of the server this client connects to. */

   struct sockaddr_in server_addr = {0}; /* Holds the server address information */
   socklen_t server_addr_len = 0u; /* Size of the struct that holds the server address information */
   ssize_t bytes_written = -1; /* The number of bytes written to the server, or -1 if read was unsuccessful. */
   size_t server_str_len = 0u; /* Size of the string read from clients. */

   char s_addr_str[INET_ADDRSTRLEN] = {0}; /* Holds the IP address to print */
   char client_str[BUFFER_SIZE] = {0}; /* Contains what a client has sent as an argument */

	printf("Starting cat laser turret TCP client.\n");

   /* Create a new socket and save entry in file descriptor table */
	sock_fd = socket(AF_INET, SOCK_STREAM, 0);
   if (sock_fd < 0) { error("ERROR: Failed to create the client socket."); }

   printf("client socket successfully created.\n");

   /* Populate the server address structure with the correct information. */
   server_addr.sin_family = AF_INET; /* Internet domain sockets address family (IPv4). */
   server_addr.sin_port = htons(PORT); /* Convert port number (short) from host byte order to network byte order. */
   server_addr.sin_addr.s_addr = inet_addr(SERVER_IP);  /* Local host address (long) converted from host byte order to network byte order. */

   /* Attempt to connect to the TCP server. */
	server_addr_len = (socklen_t) sizeof(struct sockaddr_in);
   if (connect(sock_fd, (struct sockaddr *)&server_addr, server_addr_len) < 0) {
      error("ERROR: Unable to connect to a server (connect() failed).");
   }

   /* TODO: This is a simple confirmation of a connection. Implement actually useful code. */
   bytes_written = write(sock_fd, "This is a test message!", 5);

   if (bytes_written < 0) {
      error("ERROR: Failed to write message to the server.\n");
   }

   /* Close the client socket. */
   if (close(sock_fd) < 0) {
      error("ERROR: Error closing client socket.");
   }

   return 0;
}
